---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    xdg_cache_home: "{{ ansible_user_dir }}/.cache"
    xdg_config_home: "{{ ansible_user_dir }}/.config"
    xdg_data_home: "{{ ansible_user_dir }}/.local/share"
    xdg_state_home: "{{ ansible_user_dir }}/.local/state"
    shell:
      alias_dir: "{{ xdg_config_home }}/aliases.d"
      rc: "{{ ansible_user_dir }}/.bashrc"

  pre_tasks:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
      become: true
      changed_when: false

  roles:
    - role: whalej84.gnome-desktop
      vars:
        background_picture: "'file:///usr/share/backgrounds/Monument_valley_by_orbitelambda.jpg'"
        gtk_theme: "'Yaru-sage-dark'"
        background:
          picture_uri: "{{ background_picture }}"
          picture_uri_dark: "{{ background_picture }}"
          show_desktop_icons: "false"
        calendar:
          show_weekdate: "true"
        datetime:
          automatic_timezone: "false"
        interface:
          clock_format: "'24h'"
          clock_show_weekday: "true"
          color_scheme: "'prefer-dark'"
          enable_hot_corners: "false"
          gtk_theme: "{{ gtk_theme }}"
          icon_theme: "{{ gtk_theme }}"
          show_battery_percentage: "true"
          text_scaling_factor: 1.25
        notifications:
          show_in_lock_screen: "false"
        peripherals_keyboard:
          numlock_state: "true"
        peripherals_touchpad:
          disable_while_typing: "true"
          tap_to_click: "false"
        privacy:
          disable_camera: "true"
          disable_microphone: "true"
        remote_desktop_rdp:
          enable: "false"
        remote_desktop_vnc:
          enable: "false"
        _settings_daemon_plugins_color:
          night_light_enabled: "true"
        _settings_daemon_plugins_media_keys:
          search: "['<Super>d']"
          terminal: "['<Super>Return']"
        _shell:
          favorite_apps: "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'firefox_firefox.desktop', 'signal-desktop.desktop']"
        _system_location:
          enabled: "false"
        screensaver:
          picture_uri: "{{ background_picture }}"
        shell_extensions_ding:
          show_home: "false"
        search_providers:
          disable_external: "true"
        wm_keybindings:
          close: "['<Super><Shift>q']"
          switch_to_workspace_left: "['<Control>Left']"
          switch_to_workspace_right: "['<Control>Right']"
          toggle_fullscreen: "['<Super>f']"
        wm_preferences:
          audible_bell: "false"
          focus_mode: "'sloppy'"
        install_editor: true
      tags: [gnome-desktop]

    - role: whalej84.gnome-terminal
      vars:
        audible_bell: "false"
        # Gruvbox colours
        black: "'#FBFBF1F1C7C7'"
        red: "'#CCCC24241D1D'"
        green: "'#989897971A1A'"
        yellow: "'#D7D799992121'"
        blue: "'#454585858888'"
        magenta: "'#B1B162628686'"
        cyan: "'#68689D9D6A6A'"
        white: "'#7C7C6F6F6464'"
        bright_black: "'#929283837474'"
        bright_red: "'#9D9D00000606'"
        bright_green: "'#797974740E0E'"
        bright_yellow: "'#B5B576761414'"
        bright_blue: "'#070766667878'"
        bright_magenta: "'#8F8F3F3F7171'"
        bright_cyan: "'#42427B7B5858'"
        bright_white: "'#3C3C38383636'"
        #
        background_color: "{{ black }}"
        bold_color: "{{ bright_white }}"
        cursor_background_color: "{{ bright_white }}"
        cursor_foreground_color: "{{ black }}"
        foreground_color: "{{ bright_white }}"
        palette: "[{{ black }}, {{ red }}, {{ green }}, {{ yellow }}, {{ blue }}, {{ magenta }}, {{ cyan }}, {{ white }}, {{ bright_black }}, {{ bright_red }}, {{ bright_green }}, {{ bright_yellow }}, {{ bright_blue }}, {{ bright_magenta }}, {{ bright_cyan }}, {{ bright_white }}]"
        use_theme_colors: "false"
        cursor_shape: "ibeam"
        show_scrollbar: "never"
        theme_variant: "system"
        custom_command: "tmux new-session -A -s term"
      tags: [gnome-terminal]

    - role: whalej84.tmux
      vars:
        tmux_config_dir: "{{ xdg_config_home }}/tmux"
      tags: [tmux]

    - role: whalej84.bash
      vars:
        HISTSIZE: ""
        HISTFILESIZE: ""
        HISTFILE: "{{ xdg_state_home }}/bash/history"
        inputrc: "{{ xdg_config_home }}/bash/inputrc"
        vi: true
        prompt_command: |
          'PS1_CMD1=$(git branch --show-current 2>/dev/null)'; PS1='\[\033[38;5;66m\]\W\[\e[0m\]\[\033[38;5;124m\](${PS1_CMD1})\[\e[0m\]: '
      tags: [bash]

    - role: whalej84.firefox
      vars:
        browser_aboutconfig_showwarning: "false"
        browser_uicustomization_state: '{"placements":{"widget-overflow-fixed-list":[],"unified-extensions-area":[],"nav-bar":["sidebar-button","back-button","forward-button","stop-reload-button","vertical-spacer","customizableui-special-spring1","urlbar-container","customizableui-special-spring2","downloads-button","unified-extensions-button","ublock0_raymondhill_net-browser-action"],"toolbar-menubar":["menubar-items"],"TabsToolbar":[],"vertical-tabs":["tabbrowser-tabs"],"PersonalToolbar":["personal-bookmarks"]},"seen":[],"dirtyAreaCache":["nav-bar","PersonalToolbar","toolbar-menubar","TabsToolbar","unified-extensions-area","vertical-tabs"],"currentVersion":23,"newElementCount":3}'
        prevent_default_download_pdf: "true"
        remove_close_button_from_tabs: "true"
        toolbar_bookmark_visibility: "newtab"
        startup_page_option: 0
        allow_health_reporting: "false"
        allow_study_reporting: "false"
        load_new_tab_in_background: "false"
        ask_save_passwords: "false"
        ask_use_location: 2
        ask_use_camera: 2
        ask_use_microphone: 2
        ask_notify_desktop: 2
        do_not_track: "true"
        global_privacy_control: "true"
        recommended_stories: "false"
        sponsored_shortcuts: "false"
        vertical_tabs: "true"
        sidebar_tools: "history,bookmarks"
        browser_extensions:
          - id: uBlock0@raymondhill.net
            url: https://addons.mozilla.org/firefox/downloads/file/4290466/ublock_origin-latest.xpi
          - id: keepassxc-browser@keepassxc.org
            url: https://addons.mozilla.org/firefox/downloads/file/4285762/keepassxc_browser-latest.xpi
          - id: "{3e4d2037-d300-4e95-859d-3cba866f46d3}"
            url: https://addons.mozilla.org/firefox/downloads/file/4073898/private_internet_access_ext-latest.xpi
      tags: [firefox]

    - role: whalej84.git
      vars:
        config_location: "{{ xdg_config_home }}/git/config"
        user_vars:
          email: "james@james-whale.com"
          name: "James Whale"
          signingkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOBpPvI5ze4AbkQtGG6r/9X5/imK2e27SjQF86PzQc3j james@james-whale.com"
        init_vars:
          defaultBranch: "main"
          templateDir: "{{ xdg_data_home }}/git/templates/default"
        core_vars:
          editor: "vim"
          hooksPath: "{{ xdg_data_home }}/git/hooks"
        gpg_vars:
          format: "ssh"
        gpg_ssh_vars:
          allowedSignersFile: "{{ ansible_user_dir }}/.ssh/allowed_signers"
        commit_vars:
          gpgsign: "true"
        push_vars:
          autoSetupRemote: "true"
        alias_vars:
          co: "checkout"
          br: "branch -av"
          rmbr: "branch -D"
          ci: "commit"
          st: "status -s"
          sta: "status"
          amend: "!git log -n 1 --pretty=tformat:%s%n%n%b | git commit -F - --amend"
          compare: "log -n1 -p --format=fuller"
          unstage: "reset HEAD --"
          lg: "log --graph --show-signature"
          squash: "merge --squash"
          rw: "reset --hard"
          prune: "remote prune origin"
        color_vars:
          ui: "true"
        color_branch_vars:
          current: "yellow reverse"
          local: "yellow"
          remote: "green"
        color_diff_vars:
          meta: "yellow bold"
          frag: "magenta bold"
          old: "red bold"
          new: "green bold"
        color_status_vars:
          added: "yellow"
          changed: "green"
          untracked: "red"
        url_github_vars:
          insteadOf: "gh:"
        ignore:
          - "\\.*\\.swp"
      tags: [git]

    - role: whalej84.vim
      vars:
        APT_REQUIREMENTS:
          - nodejs
          - npm
        VIM_PLUG_PLUGINS:
          - PLUG: "'neoclide/coc.nvim', {'branch': 'release'}"
            VARS:
              - LINE: 'inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"'
                COMMENT: "Use <enter> to select completion"
              - LINE: |
                  let g:coc_filetype_map = {}
                COMMENT: "Map filetypes to coc plugins"
          - PLUG: "'pearofducks/ansible-vim', { 'do': './UltiSnips/generate.sh' }"
          - PLUG: "'yaegassy/coc-ansible', {'do': 'yarn install --frozen-lockfile'}"
      tags: [vim]

    - role: whalej84.keepassxc
      vars:
        theme: "auto"
        compact_mode: "true"
        automatically_launch_keepassxc_at_system_startup: "true"
        minimize_instead_of_app_exit: "true"
        show_a_system_tray_icon: "true"
        tray_icon_type: "colorful"
        hide_window_to_system_tray_when_minimized: "true"
        enable_browser_integration: "true"
        enable_ssh_agent_integration: "true"
      tags: [keepassxc]

    - role: whalej84.syncthing
      vars:
        devices:
          - "YRAHAWR-A3XFXZC-SCMZ5BB-K5RN2Y5-47OFKLK-XJ54HJ5-QSV6NP4-JP47MQR"
          - "FBYQERZ-M45W5HZ-R7OGQ6V-5M7MX4X-GHIQ2EM-IWITNLH-O3N4HSH-4YK55AF"
        keepassxc:
          id: "gscwy-nuhan"
          label: "KeepassXC"
          path: "{{ xdg_data_home }}/keepassxc"
          type: "sendreceive"
          rescanIntervalS: "0"
          fsWatcherEnabled: "false"
          fsWatcherDelayS: "10"
          fsWatcherTimeoutS: "0"
          ignorePerms: "false"
          autoNormalize: "false"
      tags: [syncthing]

    - role: whalej84.gns3
      vars:
        iou_support: true
        new_path: "{{ xdg_data_home }}/gns3"
        images_path: "{{ new_path }}/images"
        projects_path: "{{ new_path }}/projects"
        appliances_path: "{{ new_path }}/appliances"
        symbols_path: "{{ new_path }}/symbols"
        configs_path: "{{ new_path }}/configs"
      tags: [gns3]

    - role: whalej84.signal
      tags: [signal]

    - role: whalej84.abcde
      vars:
        abcde_config: "{{ xdg_config_home }}/abcde/config"
        ABCDE_ALIASES: "{{ shell.alias_dir }}/50-abcde.conf"
        abcde_vars:
          CDDBLOCALDIR: "{{ xdg_data_home }}/cddb"
          KEEPWAVS: "n"
          CDROM: "/dev/sr0"
          OUTPUTDIR: "{{ ansible_user_dir }}/Music"
          WAVOUTPUTDIR: "{{ xdg_cache_home }}/abcde"
          OUTPUTTYPE: "m4a"
          OUTPUTFORMAT: "${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM} ${TRACKFILE}"
          MUNGEFILENAME: |
            echo "$@" | sed -e 's/^\.*//' | tr -d ":><|*/\"'?[:cntrl:]";
          EJECTCD: "y"
          aliases:
            abcde: "abcde -c {{ abcde_config }}"
      tags: [abcde]

    - role: whalej84.apple-superdrive
      tags: [apple-superdrive]

    - role: whalej84.pycharm
      tags: [pycharm]
