---
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: update apt repositories
      apt:
        update_cache: true
        cache_valid_time: 86400
      become: true
      changed_when: false
  
  roles:
    - role: whalej84.firefox
      vars:
        prevent_default_download_pdf: "true"
        remove_close_button_from_tabs: "true"
        toolbar_bookmark_visibility: "newtab"
        startup_page_option: 0
        allow_health_reporting: "false"
        allow_study_reporting: "false"
        load_new_tab_in_background: "false"
        ask_save_passwords: "false"
        ask_use_location: 2
        ask_use_camera: 2
        ask_use_microphone: 2
        ask_notify_desktop: 2
        do_not_track: "true"
        global_privacy_control: "true"
        recommended_stories: "false"
        sponsored_shortcuts: "false"
        browser_extensions:
          - id: uBlock0@raymondhill.net
            url: https://addons.mozilla.org/firefox/downloads/file/4290466/ublock_origin-latest.xpi
          - id: keepassxc-browser@keepassxc.org
            url: https://addons.mozilla.org/firefox/downloads/file/4285762/keepassxc_browser-latest.xpi
      tags: [ firefox ]
      
    - role: whalej84.keepassxc
      vars:
        theme: "light"
        compact_mode: "true"
        automatically_launch_keepassxc_at_system_startup: "true"
        minimize_instead_of_app_exit: "true"
        show_a_system_tray_icon: "true"
        enable_browser_integration: "true"
      tags: [ keepassxc ]
