---
roles:
  - name: whalej84.firefox
    src: https://github.com/WhaleJ84/ansible-role-firefox.git
    scm: git

  - name: whalej84.keepassxc
    src: https://github.com/WhaleJ84/ansible-role-keepassxc.git
    scm: git

  - name: whalej84.tmux
    src: https://github.com/WhaleJ84/ansible-role-tmux.git
    scm: git

  - name: whalej84.psutil
    src: https://github.com/WhaleJ84/ansible-role-psutil.git
    scm: git

  - name: whalej84.gnome-terminal
    src: https://github.com/WhaleJ84/ansible-role-gnome-terminal.git
    scm: git

  - name: whalej84.syncthing
    src: https://github.com/WhaleJ84/ansible-role-syncthing.git
    scm: git
