---
roles:
  - name: whalej84.firefox
    src: https://github.com/WhaleJ84/ansible-role-firefox.git
    scm: git

  - name: whalej84.keepassxc
    src: https://github.com/WhaleJ84/ansible-role-keepassxc.git
    scm: git
