---
- name: ROLE | Vim
  hosts: localhost
  roles:
    - role: whalej84.vim
      vars:
        APT_REQUIREMENTS:
          - nodejs
        VIM_PLUG_PLUGINS:
          - "Plug 'neoclide/coc.nvim', {'branch': 'release'}"
        MODIFICATIONS:
          - LINE: 'inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"'
            COMMENT: "Use <enter> to select completion"
      tags: [ vim ]

