---
- name: ROLE | Vim
  hosts: localhost
  roles:
    - role: whalej84.vim
      vars:
        APT_REQUIREMENTS:
          - nodejs
          - npm
        VIM_PLUG_PLUGINS:
          - "'neoclide/coc.nvim', {'branch': 'release'}"
          - "'pearofducks/ansible-vim', { 'do': './UltiSnips/generate.sh' }"
          - "'yaegassy/coc-ansible', {'do': 'yarn install --frozen-lockfile'}"
        MODIFICATIONS:
          - LINE: 'inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"'
            COMMENT: "Use <enter> to select completion"
      tags: [ vim ]

